#!/usr/bin/env bash
#
# basher `hosts` plugin
#
# Manage /etc/hosts
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 4/7/14
# License: MIT

nodesdir=$BASHER_DIR/nodes

debug "finding nodes in $nodesdir"
data=()
shopt -s nullglob
for file in "$nodesdir/"*.com; do
	fqdn=${file##*/}
	debug "processing $fqdn ($file)"

	ip=
	. "$file" || fatal "failed to source $fqdn ($file)"

	if [[ -n $ip ]]; then
		trace "$fqdn: IP address found as $ip"
		data+=("$fqdn $ip")
	else
		trace "$fqdn: no IP address found"
	fi
done

debug "${#data[@]} nodes with IP addresses found"

export DATA=$(for d in "${data[@]}"; do echo "$d"; done)
put_template templates/hosts.erb /etc/hosts 644 root

return 0
