#!/usr/bin/env bash
#
# basher `upgrade` plugin
#
# Upgrade `basher` to the latest version from GitHub
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 4/7/14
# License: MIT

PREFIX=${PREFIX:-/opt/local}

raw='https://raw.githubusercontent.com/bahamas10/basher/master/basher'
bin=$PREFIX/bin/basher

log "currently running basher $(basher -V)"

log "$raw -> $bin"

curl "$raw" -o "$bin" || fatal 'failed to curl'
chmod +x "$bin"

basher -h || fatal 'basher fails to execute'

log "basher $(basher -V) installed"
