#!/usr/bin/env bash
#
# SmartOS pkgin wrapper function
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 3/17/14
# License: MIT

trace 'pkgin :: defining pkgin_package'
pkgin_package() {
	local action=$1
	local pkg=$2

	log "pkgin :: $action $pkg"

	case "$action" in
		install)
			if _pkgin_package_installed "$pkg"; then
				debug "pkgin :: $pkg already installed"
				return 0
			fi
			;;
		remove)
			if ! _pkgin_package_installed "$pkg"; then
				debug "pkgin :: $pkg not present"
				return 0
			fi
			;;
		*) fatal "pkgin :: unknown action $action"
	esac

	trace "pkgin :: calling \`pkgin -y $action $pkg\`"
	pkgin -y "$action" "$pkg" || fatal "pkgin :: failed to $action $pkg"
	warn "pkgin :: $action $pkg"
	return 0
}

# check if a package is installed
_pkgin_package_installed() {
	local pkg=$1
	# so gross, this could probably be made better
	pkgin ls | grep -q "^$pkg"
}
