#!/usr/bin/env node
/**
 * List interfaces on a node without parsing `ifconfig`,
 * which can be inconsistent.  This prints interfaces
 * in the format of:
 * <name1> <ipv4>
 * <name2> <ipv4>
 *
 * Author: Dave Eddy <dave@daveeddy.com>
 * Date: 3/23/14
 * License: MIT
 */

var os = require('os');
var i = os.networkInterfaces();

Object.keys(i).forEach(function(name) {
  var ip4 = null;
  i[name].forEach(function(int) {
    if (int.family === 'IPv4')
      ip4 = int.address;
  });
  console.log('%s %s', name, ip4);
});
