#!/usr/bin/env bash
#
# SMF svcadm and svccfg wrapper function
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 3/17/14
# License: MIT

trace 'SMF :: defining smf_service'
smf_service() {
	log "SMF :: $@"

	if ! svcadm -v "$@"; then
		fatal "SMF :: failed to $@"
	fi
}
